import { useEffect, useMemo, useState } from 'react'
import { createClient } from '@supabase/supabase-js'
import './melius.css'

const SB_URL='https://tieuutosriyosykcshdn.supabase.co'
const SB_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYXNlIiwicmVmIjoidGlldXV0b3NyaXlvc3lrY3NoZG4iLCJyb2xlIjoiYW5vbiIsImlhdCI6MTc3Mjc0NTUyNCwiZXhwIjoyMDg4MzIxNTI0fQ.ixQ5dteC2coN_Lqonh1M0AmsLabYVYufVXo93F38hZU'
const supabase=createClient(SB_URL,SB_KEY)

const NAMES={1:'Perfectionism as Procrastination',2:'Addiction to Potential',3:'Comparison Paralysis',4:'Waiting to Feel Ready',5:'Overidentifying with the Past',6:'Fearing Success More Than Failure',7:'Emotional Self-Isolation',8:'Romanticizing the Struggle',9:'Financial Martyrdom',10:'Toxic Spiritual Bypassing',11:'Over-Researching, Under-Doing',12:'Seeking Constant Validation',13:'Creating Only When Inspired',14:'Creating from Wounds, Not Power',15:'Abandoning Projects Mid-Birth'}
const SHORT={1:'Perfectionism',2:'Potential Trap',3:'Comparison',4:'Not Ready',5:'Living in the Past',6:'Fearing Success',7:'Self-Isolation',8:'Romanticizing',9:'Financial Martyrdom',10:'Spiritual Bypass',11:'Over-Research',12:'Validation',13:'Inspiration-Only',14:'Creating from Wounds',15:'Abandonment'}
const DESC={1:'You use perfectionism as a shield. If it is never finished, it can never fail.',2:'The fantasy of the future self is more alive than the work in front of you.',3:"Other people's success reads as evidence of your inadequacy.",4:'You keep moving the point called ready so exposure can stay delayed.',5:'The old story protects you from having to write a new one.',6:'Visibility feels like threat. Success means being fully seen.',7:'Isolation feels like focus, but sometimes it is armor.',8:'Suffering has become proof that you are serious.',9:'Scarcity has become part of how you prove devotion to the work.',10:'Detachment becomes escape when it prevents direct contact with what is happening.',11:'Knowledge becomes a delay tactic when preparation replaces movement.',12:'The Artist makes work. The Orphan manufactures likability.',13:'Waiting for inspiration puts the work at the mercy of weather.',14:'Pain can open the portal, but power is what walks through it.',15:'You stop at the threshold because unfinished work cannot be judged.'}
const REFRAME={1:'Done and imperfect is evidence. The work needs to exist.',2:'The future self cannot save you. Present action can.',3:'Someone else’s position is not data about yours.',4:'Ready is a moving target. Move with what is true now.',6:'Being seen is the point. The work can hold witness.',7:'Letting someone in can ground the person doing the work.',11:'You will not think your way into mastery. You will move into it.',12:'Create first. Let response come second. The order matters.',14:'The wound may be the door. Do not make it the room.',15:'Finishing is the proof.'}
const QUIZ=[
['You finish a solid draft. Your first instinct is—',['It is not ready. I need to fix it.',[1],3],['I am already excited about the next idea.',[2,15],3],['I wonder what people will think.',[12],3],['I feel exposed.',[6,1],3]],
['You have not worked on the project in three days. What is the story?',['I am waiting for the right energy.',[13,4],3],['I keep getting pulled into research.',[11],3],['I am scared to see where I left it.',[15,1],3],['I have been comparing myself.',[3],3]],
['When a project gets close to done, you—',['Start a new one.',[2,15],3],['Slow down and find more to fix.',[1,15],3],['Push through with anxiety.',[6],2],['Finish, then avoid sharing.',[6,12],3]],
['Someone gives critical feedback. Your first reaction is—',["They are right. I knew it was not good enough.",[1,12],3],['Maybe this is not my thing.',[5,3],3],['I need to know if everyone agrees.',[12],3],['I want to disappear.',[7],3]],
['Where does most creative energy come from?',['Pain or something I am processing.',[14,8],3],['Momentum when I am on a roll.',[13],2],['The fantasy of what this could become.',[2],3],['Discipline. I show up anyway.',[],0]],
['You imagine yourself fully successful. Your honest reaction?',['Excited. I can see it.',[2],2],['Anxious. I am not sure I could handle it.',[6],3],['Doubtful. That version feels like someone else.',[5,6],3],['Relieved. It would finally prove something.',[12],3]],
['When blocked, what do you do?',['Research, tutorials, or reading.',[11],3],['Wait until the feeling returns.',[13,4],3],['Isolate and power through alone.',[7],3],['Start something new.',[2,15],3]],
['What does making creative work cost you?',['Sleep, money, or stability.',[9,8],3],['Relationships. I isolate.',[7],3],['Peace of mind. I am never satisfied.',[1,14],3],['Confidence. Every project makes me doubt myself.',[3,12],3]]]
const PROMPTS=[['PRE-01','What is the story you are telling yourself about this project right now?',[1,5,8]],['PRE-02','Are you about to research or are you about to create?',[11]],['PRE-03','Who are you making this for today — yourself or approval?',[12]],['PRE-05','Are you waiting to feel ready, or are you ready enough?',[4]],['PRE-06','What is the minimum you could finish today that would count as real?',[15,1]],['PRE-09','Who came to make this today — the Artist or the Orphan?',[12]],['PRE-12','Are you in your power right now, or creating from a wound?',[14]]]
const KEYWORDS={1:['perfect','not ready','fix','polish'],2:['potential','someday','new idea'],3:['compare','behind','ahead'],4:['wait','ready','later'],6:['afraid','scared','seen','exposed'],7:['alone','isolated','disappear'],8:['struggle','sacrifice','suffering'],11:['research','tutorial','learn first'],12:['approval','people think','feedback','audience'],13:['inspiration','not feeling it','blocked'],14:['pain','hurt','wound','grief'],15:['give up','abandon','quit','new project']}

const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v))
const uid=()=>Date.now()
const profileFrom=answers=>{const scores={};answers.forEach(a=>a.patterns.forEach(p=>scores[p]=(scores[p]||0)+a.weight));return Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([id,s])=>({id:+id,name:NAMES[id],short:SHORT[id],score:Math.min(99,s*11)}))}
const scan=text=>Object.entries(KEYWORDS).filter(([,words])=>words.some(w=>text.toLowerCase().includes(w))).map(([id])=>+id)

function Onboarding({onReady}){
 const [stage,setStage]=useState('intro'),[name,setName]=useState(''),[creativeType,setType]=useState(''),[q,setQ]=useState(0),[answers,setAnswers]=useState([]),[profile,setProfile]=useState(null),[email,setEmail]=useState(''),[syncState,setSyncState]=useState(''),[error,setError]=useState('')
 const data=()=>({name:name.trim(),creativeType,profile})
 const answer=opt=>{const next=[...answers,{patterns:opt[1],weight:opt[2]}];if(q<QUIZ.length-1){setAnswers(next);setQ(q+1)}else{setProfile(profileFrom(next));setStage('reveal')}}
 const enter=()=>onReady(data())
 const send=async()=>{setError('');setSyncState('sending');save('calib:pending',data());const {error:e}=await supabase.auth.signInWithOtp({email,options:{shouldCreateUser:true,emailRedirectTo:window.location.origin}});if(e){setError(e.message);setSyncState('')}else setSyncState('sent')}
 if(stage==='intro')return <div className="app full-screen"><section className="intro-copy"><div><div className="eyebrow">Creative calibration system</div><h1>calib<span className="orange">.</span></h1><p>Find the pattern underneath the stop. Then use each real session to update the map.</p></div><div className="diagram"><span className="node">contact</span><span className="arrow">→</span><span className="node">pattern</span><span className="arrow">→</span><span className="node hot">direction</span><span className="arrow">→</span><span className="node">update</span></div></section><aside className="intro-panel"><div><div className="eyebrow" style={{color:'#9c9a93'}}>Permanent access</div><div className="panel-number">Free.</div><p style={{lineHeight:1.6,color:'#bbb7af'}}>No Pro tier. No upgrade path. No session cap. Start locally now. Connect email only when you want cloud sync.</p></div><button className="action" onClick={()=>setStage('identity')}><span>Start discovery</span><span>→</span></button></aside></div>
 if(stage==='identity')return <div className="app"><div className="reveal decision"><div className="eyebrow">Before discovery</div><h1>What should the system call you?</h1><div className="form-grid"><div className="field"><label>Name</label><input value={name} onChange={e=>setName(e.target.value)} autoFocus/></div><div className="field"><label>What do you make?</label><select value={creativeType} onChange={e=>setType(e.target.value)}><option value="">Choose one</option>{['Music','Beats / Production','Visual Art','Film / Video','Writing','Other'].map(x=><option key={x}>{x}</option>)}</select></div><button className="action" disabled={!name.trim()||!creativeType} onClick={()=>setStage('quiz')}><span>Enter discovery</span><span>→</span></button></div></div></div>
 if(stage==='quiz'){const cur=QUIZ[q];return <div className="app quiz"><aside className="quiz-side"><div className="eyebrow">Discovery {q+1}/{QUIZ.length}</div><div className="progress"><span style={{height:`${((q+1)/QUIZ.length)*100}%`}}/></div><div className="brand">calib<b>.</b></div></aside><main className="quiz-main"><div className="eyebrow">One honest decision</div><h2>{cur[0]}</h2><p>Select the answer that happens, not the answer that sounds best.</p><div className="options">{cur.slice(1).map((o,i)=><button className="option" key={i} onClick={()=>answer(o)}><span>{o[0]}</span><span>→</span></button>)}</div></main></div>}
 return <div className="app"><main className="reveal"><div className="eyebrow">Discovery reveal</div><h1>Here is what is running underneath the work, {name}.</h1><div className="pattern-stack">{profile.map((p,i)=><div className={`pattern-tile ${i===0?'primary':''}`} key={p.id}><span>Pattern {String(p.id).padStart(2,'0')} · {i===0?'Primary':'Active'}</span><strong>{p.name}</strong><span>{p.score}% activation</span></div>)}</div><div className="auth-box"><div><div className="eyebrow">Enter now</div><h3>Your discovery is already saved on this device.</h3><p className="muted">Email is optional. Use it only to connect cloud sync across devices.</p></div><div className="form-grid"><button className="action" onClick={enter}><span>Enter Calib</span><span>→</span></button><div className="field"><label>Optional email for cloud sync</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@email.com"/></div>{error&&<div className="notice">{error}</div>}{syncState==='sent'?<div className="notice">Sync link sent to {email}. You can enter Calib now and connect later.</div>:<button className="action secondary" disabled={!email.includes('@')||syncState==='sending'} onClick={send}>{syncState==='sending'?'Sending…':'Send sync link'}</button>}</div></div></main></div>
}

function Choice({title,subtitle,choices,onPick}){return <div className="decision"><div className="eyebrow">One decision</div><h1>{title}</h1>{subtitle&&<p className="muted">{subtitle}</p>}<div className="choice-grid">{choices.map(([l,v])=><button key={l} className="choice" onClick={()=>onPick(v)}><span>{l}</span><span>→</span></button>)}</div></div>}
function Prompt({prompt,value,onChange,onNext,final}){return <div className="decision"><div className="eyebrow">{prompt[0]}</div><h1>{prompt[1]}</h1><textarea value={value} onChange={e=>onChange(e.target.value)} placeholder="Write what is true now."/><button className="action" style={{marginTop:16}} onClick={onNext}><span>{final?'Save session':'Next decision'}</span><span>→</span></button></div>}

function SessionFlow({projects,profile,onSave,onExit}){
 const prompts=useMemo(()=>{const ids=profile.map(p=>p.id);return [...PROMPTS.filter(p=>p[2].some(id=>ids.includes(id))),...PROMPTS.filter(p=>!p[2].some(id=>ids.includes(id)))].slice(0,2)},[profile])
 const [step,setStep]=useState(0),[project,setProject]=useState(null),[phase,setPhase]=useState(''),[ao,setAo]=useState(''),[energy,setEnergy]=useState(3),[responses,setResponses]=useState({})
 const finish=()=>{const structural=[];if(ao==='orphan')structural.push(12);if(phase==='Stuck')structural.push(1,4);if(energy<=2)structural.push(8,13);const keyword=scan(Object.values(responses).join(' '));const detected=[...new Set([...structural,...keyword])];onSave({id:uid(),date:new Date().toISOString(),projectId:project?.id,projectTitle:project?.title||'Unlinked session',phase,ao,energy,answers:responses,detectedPatterns:detected,keywordPatterns:keyword,structuralPatterns:structural})}
 const screens=[
 <Choice title="Which project is moving today?" choices={[...projects.filter(p=>p.status==='active').map(p=>[p.title,p]),['No specific project',null]]} onPick={v=>{setProject(v);setStep(1)}}/>,
 <Choice title="What phase is the work actually in?" choices={['Starting fresh','Grinding through','Almost done','Stuck'].map(x=>[x,x])} onPick={v=>{setPhase(v);setStep(2)}}/>,
 <Choice title="Who came to make this today?" subtitle="The Artist makes from identity. The Orphan makes for response." choices={[["Artist",'artist'],['Orphan','orphan'],['Unsure','unsure']]} onPick={v=>{setAo(v);setStep(3)}}/>,
 <Choice title="What is the energy level before movement?" choices={[1,2,3,4,5].map(x=>[String(x),x])} onPick={v=>{setEnergy(v);setStep(4)}}/>,
 <Prompt prompt={prompts[0]} value={responses[prompts[0][0]]||''} onChange={v=>setResponses({...responses,[prompts[0][0]]:v})} onNext={()=>setStep(5)}/>,
 <Prompt prompt={prompts[1]} value={responses[prompts[1][0]]||''} onChange={v=>setResponses({...responses,[prompts[1][0]]:v})} onNext={()=>{finish();setStep(6)}} final/>,
 <div className="decision"><div className="eyebrow">Session recorded</div><h1>Reality answered. The map has moved.</h1><div className="diagram"><span className="node">state</span><span className="arrow">→</span><span className="node">mechanism</span><span className="arrow">→</span><span className="node hot">direction</span><span className="arrow">→</span><span className="node">update</span></div><button className="action" onClick={onExit}><span>Return home</span><span>→</span></button></div>]
 return <div className="content">{screens[step]}</div>
}

function Main({user,sessions,projects,setSessions,setProjects,onReset,authUser,onConnect}){
 const [screen,setScreen]=useState('home'),[modal,setModal]=useState(false),[title,setTitle]=useState(''),[type,setType]=useState('Track'),[activePattern,setActivePattern]=useState(null)
 const saveProjects=next=>{setProjects(next);save('calib:projects',next);supabase.auth.getSession().then(({data:{session}})=>session&&next.forEach(p=>supabase.from('projects').upsert({id:p.id,user_id:session.user.id,data:p,updated_at:new Date().toISOString()},{onConflict:'id'})))}
 const add=()=>{if(!title.trim())return;saveProjects([...projects,{id:uid(),title:title.trim(),type,status:'active',sessions:0,phase:'starting',created:new Date().toISOString()}]);setTitle('');setModal(false)}
 const saveSession=s=>{const next=[...sessions,s];setSessions(next);save('calib:sessions',next);if(s.projectId)saveProjects(projects.map(p=>p.id===s.projectId?{...p,sessions:(p.sessions||0)+1,lastSession:s.date}:p));supabase.auth.getSession().then(({data:{session}})=>session&&supabase.from('sessions').upsert({id:s.id,user_id:session.user.id,data:s,created_at:s.date},{onConflict:'id'}))}
 const top=user.profile.map(p=>({...p,score:Math.min(99,p.score+sessions.filter(s=>s.detectedPatterns?.includes(p.id)).length*5)})).sort((a,b)=>b.score-a.score)
 const artist=Math.round((sessions.filter(s=>s.ao==='artist').length/Math.max(1,sessions.length))*100)
 const nav=[['home','Home'],['session','Session'],['projects','Projects'],['history','History'],['patterns','Patterns']]
 if(screen==='session')return <div className="app"><div className="shell"><header className="topbar"><div className="brand">calib<b>.</b></div><button className="action secondary" onClick={()=>setScreen('home')}>Exit</button></header><SessionFlow projects={projects} profile={user.profile} onSave={saveSession} onExit={()=>setScreen('home')}/></div></div>
 return <div className="app"><div className="shell"><header className="topbar"><div className="brand">calib<b>.</b></div><div className="topmeta"><span>{user.name}</span><span className="free">{authUser?'Cloud synced':'Saved on device'}</span></div></header><div className="layout"><aside className="side"><nav className="nav">{nav.map(([k,l])=><button key={k} className={screen===k?'active':''} onClick={()=>{setScreen(k);setActivePattern(null)}}>{l}</button>)}</nav><div className="side-note">Calib is a deterministic creative calibration system. Future coaching belongs to human community.</div>{!authUser&&<button className="action secondary" onClick={onConnect}>Connect cloud sync</button>}</aside><main className="content">
 {screen==='home'&&<><div className="hero"><div className="hero-copy"><div className="eyebrow">Current direction</div><h1>The next move is contact with the work.</h1><p>Your profile identifies the patterns most likely to distort movement. Each logged session updates the record without replacing your judgment.</p><div className="diagram"><span className="node">observe</span><span className="arrow">→</span><span className="node">locate</span><span className="arrow">→</span><span className="node hot">move</span><span className="arrow">→</span><span className="node">update</span></div><button className="action" onClick={()=>setScreen('session')}><span>Start session</span><span>→</span></button></div><div className="black-panel"><div><div className="panel-caption">Primary pattern</div><div className="panel-number">{String(top[0]?.id||1).padStart(2,'0')}</div></div><div><h3 className="serif" style={{fontSize:32,fontWeight:400,margin:'0 0 8px'}}>{top[0]?.name}</h3><p style={{color:'#aaa69e',lineHeight:1.55}}>{DESC[top[0]?.id]}</p></div></div></div><div className="stat-row"><div className="stat"><strong>{sessions.length}</strong><span>Sessions</span></div><div className="stat"><strong>{artist}%</strong><span>Artist rate</span></div><div className="stat"><strong>{projects.filter(p=>p.status==='active').length}</strong><span>Active projects</span></div><div className="stat"><strong>{top[0]?.score||0}%</strong><span>Top activation</span></div></div><div className="section-head"><h2>Live projects</h2><button className="action secondary" onClick={()=>setModal(true)}>Add project</button></div><div className="list">{projects.filter(p=>p.status==='active').map((p,i)=><div className="row" key={p.id} onClick={()=>setScreen('projects')}><div className="row-num">{String(i+1).padStart(2,'0')}</div><div><div className="row-title">{p.title}</div><div className="row-meta">{p.type} · {p.phase}</div></div><div className="row-meta">{p.sessions||0} sessions</div></div>)}{!projects.length&&<div className="card"><h3>No project in motion yet.</h3><p>Add the real work. Calib only gains weight through contact.</p></div>}</div></>}
 {screen==='projects'&&<><div className="section-head"><div><div className="eyebrow">Work in motion</div><h2>Projects</h2></div><button className="action" onClick={()=>setModal(true)}>Add project</button></div><div className="grid2">{projects.map(p=><div className="card" key={p.id}><div className="eyebrow">{p.type} · {p.status}</div><h3>{p.title}</h3><p>{p.sessions||0} sessions · phase: {p.phase||'starting'}</p><div className="button-row"><button className="action secondary" onClick={()=>saveProjects(projects.map(x=>x.id===p.id?{...x,status:x.status==='active'?'completed':'active'}:x))}>{p.status==='active'?'Complete':'Reactivate'}</button></div></div>)}</div></>}
 {screen==='history'&&<><div className="eyebrow">Recorded contact</div><h1 className="screen-title">Session history.</h1><div className="list">{[...sessions].reverse().map(s=><div className="row" key={s.id}><div className="row-num">{new Date(s.date).toLocaleDateString()}</div><div><div className="row-title">{s.projectTitle}</div><div className="row-meta">{s.phase} · {s.ao} · energy {s.energy}/5</div></div><div className="row-meta">{(s.detectedPatterns||[]).slice(0,2).map(id=>SHORT[id]).join(' · ')||'clean contact'}</div></div>)}{!sessions.length&&<div className="card"><h3>No sessions yet.</h3><p>The record starts when you move.</p></div>}</div></>}
 {screen==='patterns'&&!activePattern&&<><div className="eyebrow">Deterministic library</div><h1 className="screen-title">The 15 patterns.</h1><div className="list">{Object.entries(NAMES).map(([id,name])=><div className="row" key={id} onClick={()=>setActivePattern(+id)}><div className="row-num">{String(id).padStart(2,'0')}</div><div className="row-title">{name}</div><div className="row-meta">{sessions.filter(s=>s.detectedPatterns?.includes(+id)).length} session signals</div></div>)}</div></>}
 {screen==='patterns'&&activePattern&&<div className="pattern-detail"><button className="action secondary" onClick={()=>setActivePattern(null)}>← All patterns</button><div className="eyebrow" style={{marginTop:30}}>Pattern {String(activePattern).padStart(2,'0')}</div><h1>{NAMES[activePattern]}</h1><p style={{fontSize:18,lineHeight:1.7}}>{DESC[activePattern]}</p>{REFRAME[activePattern]&&<div className="quote">{REFRAME[activePattern]}</div>}<div className="black-panel" style={{minHeight:150}}><div className="panel-caption">Your record</div><div className="panel-number">{sessions.filter(s=>s.detectedPatterns?.includes(activePattern)).length}</div><div className="panel-caption">session detections</div></div></div>}
 <button className="action secondary" style={{marginTop:50}} onClick={onReset}>Reset local profile</button>
 </main></div>{modal&&<div className="modal-bg" onClick={()=>setModal(false)}><div className="modal" onClick={e=>e.stopPropagation()}><h2>Add a real project.</h2><div className="form-grid"><div className="field"><label>Project title</label><input value={title} onChange={e=>setTitle(e.target.value)} autoFocus/></div><div className="field"><label>Type</label><select value={type} onChange={e=>setType(e.target.value)}>{['Track','EP','Album','Visual','Film','Writing','Other'].map(x=><option key={x}>{x}</option>)}</select></div></div><div className="button-row"><button className="action secondary" onClick={()=>setModal(false)}>Cancel</button><button className="action" onClick={add}>Add project</button></div></div></div>}</div></div>
}

function SyncModal({onClose}){
 const [email,setEmail]=useState(''),[state,setState]=useState(''),[error,setError]=useState('')
 const send=async()=>{setState('sending');setError('');const {error:e}=await supabase.auth.signInWithOtp({email,options:{shouldCreateUser:true,emailRedirectTo:window.location.origin}});if(e){setError(e.message);setState('')}else setState('sent')}
 return <div className="modal-bg" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="eyebrow">Optional cloud sync</div><h2>Connect this device.</h2><p className="muted">Calib already works without email. A magic link only connects this local record to Supabase.</p><div className="form-grid"><div className="field"><label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoFocus/></div>{error&&<div className="notice">{error}</div>}{state==='sent'?<div className="notice">Link sent. You can keep using Calib while you connect.</div>:<button className="action" disabled={!email.includes('@')||state==='sending'} onClick={send}>{state==='sending'?'Sending…':'Send sync link'}</button>}<button className="action secondary" onClick={onClose}>Close</button></div></div></div>
}

export default function CalibMelius(){
 const [loading,setLoading]=useState(true),[authUser,setAuthUser]=useState(null),[user,setUser]=useState(()=>load('calib:user',null)),[sessions,setSessions]=useState(()=>load('calib:sessions',[])),[projects,setProjects]=useState(()=>load('calib:projects',[])),[syncOpen,setSyncOpen]=useState(false)
 useEffect(()=>{let live=true;const hydrate=async session=>{if(!live)return;setAuthUser(session?.user||null);if(!session?.user)return;const id=session.user.id;const pending=load('calib:pending',null);const [{data:p},{data:s},{data:pr}]=await Promise.all([supabase.from('profiles').select('*').eq('id',id).maybeSingle(),supabase.from('sessions').select('*').eq('user_id',id).order('created_at'),supabase.from('projects').select('*').eq('user_id',id)]);const nextUser=p?.data||pending||load('calib:user',null);if(nextUser){setUser(nextUser);save('calib:user',nextUser);await supabase.from('profiles').upsert({id,data:nextUser,updated_at:new Date().toISOString()},{onConflict:'id'})}if(s?.length){const rows=s.map(x=>x.data);setSessions(rows);save('calib:sessions',rows)}if(pr?.length){const rows=pr.map(x=>x.data);setProjects(rows);save('calib:projects',rows)}localStorage.removeItem('calib:pending')};supabase.auth.getSession().then(({data:{session}})=>hydrate(session).finally(()=>setLoading(false)));const {data:{subscription}}=supabase.auth.onAuthStateChange((_,session)=>hydrate(session));return()=>{live=false;subscription.unsubscribe()}},[])
 const ready=async data=>{setUser(data);save('calib:user',data);const {data:{session}}=await supabase.auth.getSession();if(session)await supabase.from('profiles').upsert({id:session.user.id,data,updated_at:new Date().toISOString()},{onConflict:'id'})}
 const reset=()=>{if(!confirm('Reset local Calib data?'))return;['calib:user','calib:sessions','calib:projects','calib:pending'].forEach(k=>localStorage.removeItem(k));setUser(null);setSessions([]);setProjects([])}
 if(loading)return <div className="app" style={{display:'grid',placeItems:'center'}}><div className="brand">calib<b>.</b></div></div>
 if(!user)return <Onboarding onReady={ready}/>
 return <><Main user={user} sessions={sessions} projects={projects} setSessions={setSessions} setProjects={setProjects} onReset={reset} authUser={authUser} onConnect={()=>setSyncOpen(true)}/>{syncOpen&&<SyncModal onClose={()=>setSyncOpen(false)}/>}</>
}
